# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1209, 754)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icons/OceanDAC.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_4 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.widget = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(250, 0))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.tabWidget = QtGui.QTabWidget(self.widget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 231, 661))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(231, 0))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.acquisition_btn = QtGui.QPushButton(self.tab)
        self.acquisition_btn.setGeometry(QtCore.QRect(40, 220, 150, 40))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.acquisition_btn.sizePolicy().hasHeightForWidth())
        self.acquisition_btn.setSizePolicy(sizePolicy)
        self.acquisition_btn.setMinimumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.acquisition_btn.setFont(font)
        self.acquisition_btn.setObjectName(_fromUtf8("acquisition_btn"))
        self.layoutWidget = QtGui.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(13, 24, 201, 158))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.acq_int_time_btn = QtGui.QSpinBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.acq_int_time_btn.sizePolicy().hasHeightForWidth())
        self.acq_int_time_btn.setSizePolicy(sizePolicy)
        self.acq_int_time_btn.setMinimumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.acq_int_time_btn.setFont(font)
        self.acq_int_time_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.acq_int_time_btn.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.acq_int_time_btn.setMaximum(99999)
        self.acq_int_time_btn.setObjectName(_fromUtf8("acq_int_time_btn"))
        self.gridLayout.addWidget(self.acq_int_time_btn, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.acq_avg_scan_btn = QtGui.QSpinBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.acq_avg_scan_btn.sizePolicy().hasHeightForWidth())
        self.acq_avg_scan_btn.setSizePolicy(sizePolicy)
        self.acq_avg_scan_btn.setMinimumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.acq_avg_scan_btn.setFont(font)
        self.acq_avg_scan_btn.setMaximum(99999)
        self.acq_avg_scan_btn.setObjectName(_fromUtf8("acq_avg_scan_btn"))
        self.gridLayout.addWidget(self.acq_avg_scan_btn, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.acq_boxcar_btn = QtGui.QSpinBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.acq_boxcar_btn.sizePolicy().hasHeightForWidth())
        self.acq_boxcar_btn.setSizePolicy(sizePolicy)
        self.acq_boxcar_btn.setMinimumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.acq_boxcar_btn.setFont(font)
        self.acq_boxcar_btn.setMaximum(99999)
        self.acq_boxcar_btn.setObjectName(_fromUtf8("acq_boxcar_btn"))
        self.gridLayout.addWidget(self.acq_boxcar_btn, 2, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.splitter_2 = QtGui.QSplitter(self.layoutWidget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.acq_darkcorr_btn = QtGui.QCheckBox(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.acq_darkcorr_btn.sizePolicy().hasHeightForWidth())
        self.acq_darkcorr_btn.setSizePolicy(sizePolicy)
        self.acq_darkcorr_btn.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.acq_darkcorr_btn.setText(_fromUtf8(""))
        self.acq_darkcorr_btn.setObjectName(_fromUtf8("acq_darkcorr_btn"))
        self.gridLayout.addWidget(self.splitter_2, 3, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.splitter_3 = QtGui.QSplitter(self.layoutWidget)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.acq_nonlinear_btn = QtGui.QCheckBox(self.splitter_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.acq_nonlinear_btn.sizePolicy().hasHeightForWidth())
        self.acq_nonlinear_btn.setSizePolicy(sizePolicy)
        self.acq_nonlinear_btn.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.acq_nonlinear_btn.setText(_fromUtf8(""))
        self.acq_nonlinear_btn.setObjectName(_fromUtf8("acq_nonlinear_btn"))
        self.gridLayout.addWidget(self.splitter_3, 4, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 5, 0, 1, 1)
        self.splitter_4 = QtGui.QSplitter(self.layoutWidget)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName(_fromUtf8("splitter_4"))
        self.acq_strobeLamp_btn = QtGui.QCheckBox(self.splitter_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.acq_strobeLamp_btn.sizePolicy().hasHeightForWidth())
        self.acq_strobeLamp_btn.setSizePolicy(sizePolicy)
        self.acq_strobeLamp_btn.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.acq_strobeLamp_btn.setText(_fromUtf8(""))
        self.acq_strobeLamp_btn.setObjectName(_fromUtf8("acq_strobeLamp_btn"))
        self.gridLayout.addWidget(self.splitter_4, 5, 1, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.calib_action_btn = QtGui.QPushButton(self.tab_2)
        self.calib_action_btn.setGeometry(QtCore.QRect(10, 220, 200, 40))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calib_action_btn.sizePolicy().hasHeightForWidth())
        self.calib_action_btn.setSizePolicy(sizePolicy)
        self.calib_action_btn.setMinimumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.calib_action_btn.setFont(font)
        self.calib_action_btn.setObjectName(_fromUtf8("calib_action_btn"))
        self.widget1 = QtGui.QWidget(self.tab_2)
        self.widget1.setGeometry(QtCore.QRect(2, 22, 221, 142))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.gridLayout_5 = QtGui.QGridLayout(self.widget1)
        self.gridLayout_5.setVerticalSpacing(15)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.calib_export_calib_btn = QtGui.QPushButton(self.widget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calib_export_calib_btn.sizePolicy().hasHeightForWidth())
        self.calib_export_calib_btn.setSizePolicy(sizePolicy)
        self.calib_export_calib_btn.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.calib_export_calib_btn.setFont(font)
        self.calib_export_calib_btn.setObjectName(_fromUtf8("calib_export_calib_btn"))
        self.gridLayout_5.addWidget(self.calib_export_calib_btn, 0, 0, 1, 1)
        self.calib_import_calib_btn = QtGui.QPushButton(self.widget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calib_import_calib_btn.sizePolicy().hasHeightForWidth())
        self.calib_import_calib_btn.setSizePolicy(sizePolicy)
        self.calib_import_calib_btn.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.calib_import_calib_btn.setFont(font)
        self.calib_import_calib_btn.setObjectName(_fromUtf8("calib_import_calib_btn"))
        self.gridLayout_5.addWidget(self.calib_import_calib_btn, 1, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_8 = QtGui.QLabel(self.widget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout.addWidget(self.label_8)
        self.calib_threshold_entry = QtGui.QDoubleSpinBox(self.widget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calib_threshold_entry.sizePolicy().hasHeightForWidth())
        self.calib_threshold_entry.setSizePolicy(sizePolicy)
        self.calib_threshold_entry.setMinimumSize(QtCore.QSize(50, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.calib_threshold_entry.setFont(font)
        self.calib_threshold_entry.setMaximum(1.0)
        self.calib_threshold_entry.setSingleStep(0.1)
        self.calib_threshold_entry.setProperty("value", 0.15)
        self.calib_threshold_entry.setObjectName(_fromUtf8("calib_threshold_entry"))
        self.horizontalLayout.addWidget(self.calib_threshold_entry)
        self.gridLayout_5.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.calib_fit_btn = QtGui.QPushButton(self.widget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calib_fit_btn.sizePolicy().hasHeightForWidth())
        self.calib_fit_btn.setSizePolicy(sizePolicy)
        self.calib_fit_btn.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.calib_fit_btn.setFont(font)
        self.calib_fit_btn.setObjectName(_fromUtf8("calib_fit_btn"))
        self.gridLayout_5.addWidget(self.calib_fit_btn, 3, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.gridLayout_4.addWidget(self.widget, 0, 0, 1, 1)
        self.fig_box = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fig_box.sizePolicy().hasHeightForWidth())
        self.fig_box.setSizePolicy(sizePolicy)
        self.fig_box.setObjectName(_fromUtf8("fig_box"))
        self.fig_box_layout = QtGui.QVBoxLayout(self.fig_box)
        self.fig_box_layout.setObjectName(_fromUtf8("fig_box_layout"))
        self.gridLayout_4.addWidget(self.fig_box, 0, 1, 1, 1)
        self.widget_3 = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setMinimumSize(QtCore.QSize(380, 0))
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.tabWidget_2 = QtGui.QTabWidget(self.widget_3)
        self.tabWidget_2.setGeometry(QtCore.QRect(10, 10, 361, 271))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_2.sizePolicy().hasHeightForWidth())
        self.tabWidget_2.setSizePolicy(sizePolicy)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.ruby_hydro_btn = QtGui.QRadioButton(self.tab_3)
        self.ruby_hydro_btn.setGeometry(QtCore.QRect(10, 10, 161, 17))
        self.ruby_hydro_btn.setChecked(True)
        self.ruby_hydro_btn.setObjectName(_fromUtf8("ruby_hydro_btn"))
        self.rubyBtnGroup = QtGui.QButtonGroup(MainWindow)
        self.rubyBtnGroup.setObjectName(_fromUtf8("rubyBtnGroup"))
        self.rubyBtnGroup.addButton(self.ruby_hydro_btn)
        self.ruby_non_hydro_btn = QtGui.QRadioButton(self.tab_3)
        self.ruby_non_hydro_btn.setGeometry(QtCore.QRect(180, 10, 161, 17))
        self.ruby_non_hydro_btn.setObjectName(_fromUtf8("ruby_non_hydro_btn"))
        self.rubyBtnGroup.addButton(self.ruby_non_hydro_btn)
        self.label_9 = QtGui.QLabel(self.tab_3)
        self.label_9.setGeometry(QtCore.QRect(80, 30, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.layoutWidget1 = QtGui.QWidget(self.tab_3)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 60, 331, 181))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setVerticalSpacing(6)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_21 = QtGui.QLabel(self.layoutWidget1)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_2.addWidget(self.label_21, 6, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.layoutWidget1)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 3, 0, 1, 1)
        self.fitted_y0 = QtGui.QLabel(self.layoutWidget1)
        self.fitted_y0.setObjectName(_fromUtf8("fitted_y0"))
        self.gridLayout_2.addWidget(self.fitted_y0, 0, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.layoutWidget1)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 2, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.layoutWidget1)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 1, 0, 1, 1)
        self.fitted_w = QtGui.QLabel(self.layoutWidget1)
        self.fitted_w.setObjectName(_fromUtf8("fitted_w"))
        self.gridLayout_2.addWidget(self.fitted_w, 3, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.layoutWidget1)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_2.addWidget(self.label_14, 4, 0, 1, 1)
        self.ruby_lambda0_btn = QtGui.QLineEdit(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ruby_lambda0_btn.sizePolicy().hasHeightForWidth())
        self.ruby_lambda0_btn.setSizePolicy(sizePolicy)
        self.ruby_lambda0_btn.setMinimumSize(QtCore.QSize(61, 21))
        self.ruby_lambda0_btn.setObjectName(_fromUtf8("ruby_lambda0_btn"))
        self.gridLayout_2.addWidget(self.ruby_lambda0_btn, 5, 1, 1, 1)
        self.label_20 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_2.addWidget(self.label_20, 5, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.layoutWidget1)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 1)
        self.fitted_xc = QtGui.QLabel(self.layoutWidget1)
        self.fitted_xc.setObjectName(_fromUtf8("fitted_xc"))
        self.gridLayout_2.addWidget(self.fitted_xc, 1, 1, 1, 1)
        self.fitted_A = QtGui.QLabel(self.layoutWidget1)
        self.fitted_A.setObjectName(_fromUtf8("fitted_A"))
        self.gridLayout_2.addWidget(self.fitted_A, 2, 1, 1, 1)
        self.temp_spin_btn = QtGui.QDoubleSpinBox(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.temp_spin_btn.sizePolicy().hasHeightForWidth())
        self.temp_spin_btn.setSizePolicy(sizePolicy)
        self.temp_spin_btn.setMinimumSize(QtCore.QSize(61, 21))
        self.temp_spin_btn.setDecimals(1)
        self.temp_spin_btn.setMaximum(1000.0)
        self.temp_spin_btn.setProperty("value", 298.0)
        self.temp_spin_btn.setObjectName(_fromUtf8("temp_spin_btn"))
        self.gridLayout_2.addWidget(self.temp_spin_btn, 6, 1, 1, 1)
        self.fitted_mu = QtGui.QLabel(self.layoutWidget1)
        self.fitted_mu.setObjectName(_fromUtf8("fitted_mu"))
        self.gridLayout_2.addWidget(self.fitted_mu, 4, 1, 1, 1)
        self.tabWidget_2.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.Samarium_non_hydro_btn = QtGui.QRadioButton(self.tab_4)
        self.Samarium_non_hydro_btn.setGeometry(QtCore.QRect(190, 10, 161, 17))
        self.Samarium_non_hydro_btn.setObjectName(_fromUtf8("Samarium_non_hydro_btn"))
        self.samariumBtnGroup = QtGui.QButtonGroup(MainWindow)
        self.samariumBtnGroup.setObjectName(_fromUtf8("samariumBtnGroup"))
        self.samariumBtnGroup.addButton(self.Samarium_non_hydro_btn)
        self.label_22 = QtGui.QLabel(self.tab_4)
        self.label_22.setGeometry(QtCore.QRect(80, 30, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.layoutWidget2 = QtGui.QWidget(self.tab_4)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 60, 331, 181))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget2)
        self.gridLayout_3.setVerticalSpacing(6)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.sum_fitted_y0 = QtGui.QLabel(self.layoutWidget2)
        self.sum_fitted_y0.setObjectName(_fromUtf8("sum_fitted_y0"))
        self.gridLayout_3.addWidget(self.sum_fitted_y0, 0, 1, 1, 1)
        self.label_27 = QtGui.QLabel(self.layoutWidget2)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_3.addWidget(self.label_27, 2, 0, 1, 1)
        self.sum_fitted_xc = QtGui.QLabel(self.layoutWidget2)
        self.sum_fitted_xc.setObjectName(_fromUtf8("sum_fitted_xc"))
        self.gridLayout_3.addWidget(self.sum_fitted_xc, 1, 1, 1, 1)
        self.sum_fitted_A = QtGui.QLabel(self.layoutWidget2)
        self.sum_fitted_A.setObjectName(_fromUtf8("sum_fitted_A"))
        self.gridLayout_3.addWidget(self.sum_fitted_A, 2, 1, 1, 1)
        self.sum_fitted_mu = QtGui.QLabel(self.layoutWidget2)
        self.sum_fitted_mu.setObjectName(_fromUtf8("sum_fitted_mu"))
        self.gridLayout_3.addWidget(self.sum_fitted_mu, 4, 1, 1, 1)
        self.label_29 = QtGui.QLabel(self.layoutWidget2)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_3.addWidget(self.label_29, 3, 0, 1, 1)
        self.label_25 = QtGui.QLabel(self.layoutWidget2)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_3.addWidget(self.label_25, 1, 0, 1, 1)
        self.label_31 = QtGui.QLabel(self.layoutWidget2)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_3.addWidget(self.label_31, 4, 0, 1, 1)
        self.sum_fitted_w = QtGui.QLabel(self.layoutWidget2)
        self.sum_fitted_w.setObjectName(_fromUtf8("sum_fitted_w"))
        self.gridLayout_3.addWidget(self.sum_fitted_w, 3, 1, 1, 1)
        self.label_23 = QtGui.QLabel(self.layoutWidget2)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_3.addWidget(self.label_23, 0, 0, 1, 1)
        self.label_33 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        self.label_33.setFont(font)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_3.addWidget(self.label_33, 5, 0, 1, 1)
        self.Samarium_lambda0_btn = QtGui.QLineEdit(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Samarium_lambda0_btn.sizePolicy().hasHeightForWidth())
        self.Samarium_lambda0_btn.setSizePolicy(sizePolicy)
        self.Samarium_lambda0_btn.setMinimumSize(QtCore.QSize(61, 21))
        self.Samarium_lambda0_btn.setObjectName(_fromUtf8("Samarium_lambda0_btn"))
        self.gridLayout_3.addWidget(self.Samarium_lambda0_btn, 5, 1, 1, 1)
        self.Samarium_hydro_btn = QtGui.QRadioButton(self.tab_4)
        self.Samarium_hydro_btn.setGeometry(QtCore.QRect(10, 10, 171, 17))
        self.Samarium_hydro_btn.setChecked(True)
        self.Samarium_hydro_btn.setObjectName(_fromUtf8("Samarium_hydro_btn"))
        self.samariumBtnGroup.addButton(self.Samarium_hydro_btn)
        self.tabWidget_2.addTab(self.tab_4, _fromUtf8(""))
        self.pressure_txt = QtGui.QLabel(self.widget_3)
        self.pressure_txt.setGeometry(QtCore.QRect(20, 290, 251, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pressure_txt.setFont(font)
        self.pressure_txt.setObjectName(_fromUtf8("pressure_txt"))
        self.pressure_monitor = QtGui.QWidget(self.widget_3)
        self.pressure_monitor.setGeometry(QtCore.QRect(10, 360, 361, 301))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pressure_monitor.sizePolicy().hasHeightForWidth())
        self.pressure_monitor.setSizePolicy(sizePolicy)
        self.pressure_monitor.setObjectName(_fromUtf8("pressure_monitor"))
        self.pressure_monitor_layout = QtGui.QVBoxLayout(self.pressure_monitor)
        self.pressure_monitor_layout.setObjectName(_fromUtf8("pressure_monitor_layout"))
        self.splitter = QtGui.QSplitter(self.widget_3)
        self.splitter.setGeometry(QtCore.QRect(20, 330, 351, 23))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.monitor_pressure_btn = QtGui.QPushButton(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.monitor_pressure_btn.sizePolicy().hasHeightForWidth())
        self.monitor_pressure_btn.setSizePolicy(sizePolicy)
        self.monitor_pressure_btn.setObjectName(_fromUtf8("monitor_pressure_btn"))
        self.export_pressure_btn = QtGui.QPushButton(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.export_pressure_btn.sizePolicy().hasHeightForWidth())
        self.export_pressure_btn.setSizePolicy(sizePolicy)
        self.export_pressure_btn.setObjectName(_fromUtf8("export_pressure_btn"))
        self.gridLayout_4.addWidget(self.widget_3, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusbar.sizePolicy().hasHeightForWidth())
        self.statusbar.setSizePolicy(sizePolicy)
        self.statusbar.setMinimumSize(QtCore.QSize(0, 30))
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setAcceptDrops(True)
        self.toolBar.setAllowedAreas(QtCore.Qt.NoToolBarArea)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionRefresh = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("icons/Button-Refresh-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRefresh.setIcon(icon1)
        self.actionRefresh.setPriority(QtGui.QAction.HighPriority)
        self.actionRefresh.setObjectName(_fromUtf8("actionRefresh"))
        self.actionRecord = QtGui.QAction(MainWindow)
        self.actionRecord.setCheckable(True)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("icons/Button-Blank-Red-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRecord.setIcon(icon2)
        self.actionRecord.setPriority(QtGui.QAction.HighPriority)
        self.actionRecord.setObjectName(_fromUtf8("actionRecord"))
        self.actionDark = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("icons/Button-Blank-Gray-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDark.setIcon(icon3)
        self.actionDark.setObjectName(_fromUtf8("actionDark"))
        self.actionZoom = QtGui.QAction(MainWindow)
        self.actionZoom.setCheckable(True)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("icons/Perspective-Button-Search-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoom.setIcon(icon4)
        self.actionZoom.setObjectName(_fromUtf8("actionZoom"))
        self.actionSave = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("icons/Button-Download-icon-2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon5)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionAbout = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("icons/Button-Info-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon6)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.toolBar.addAction(self.actionRefresh)
        self.toolBar.addAction(self.actionRecord)
        self.toolBar.addAction(self.actionDark)
        self.toolBar.addAction(self.actionZoom)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.actionAbout)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Ocean Optics Spectrometer - ", None))
        self.acquisition_btn.setToolTip(_translate("MainWindow", "Capture single ruby spectrum and calculate the pressure.", None))
        self.acquisition_btn.setText(_translate("MainWindow", "Capture spectrum", None))
        self.label_2.setText(_translate("MainWindow", "Integration time (ms)", None))
        self.label_3.setText(_translate("MainWindow", "Scans to average", None))
        self.label_4.setText(_translate("MainWindow", "Boxcar pixels", None))
        self.label_5.setText(_translate("MainWindow", "Dark current correction", None))
        self.label_6.setText(_translate("MainWindow", "Non-linearity correction", None))
        self.label_7.setText(_translate("MainWindow", "Enable strobe/lamp", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Acquisition", None))
        self.calib_action_btn.setText(_translate("MainWindow", "Click to calibrate", None))
        self.calib_export_calib_btn.setText(_translate("MainWindow", "Export current calibration", None))
        self.calib_import_calib_btn.setText(_translate("MainWindow", "Import calibration", None))
        self.label_8.setText(_translate("MainWindow", "Peaks detection threshold", None))
        self.calib_fit_btn.setText(_translate("MainWindow", "Capture Neon spectrum", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Calibration", None))
        self.ruby_hydro_btn.setText(_translate("MainWindow", "Hydrostatic (Dewaele 2008)", None))
        self.ruby_non_hydro_btn.setText(_translate("MainWindow", "Non-hydrostatic (Mao 1986)", None))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">Fitted results (Ruby peak R1)</span></p></body></html>", None))
        self.label_21.setText(_translate("MainWindow", "T (K)", None))
        self.label_13.setText(_translate("MainWindow", "FWHM", None))
        self.fitted_y0.setText(_translate("MainWindow", "BG", None))
        self.label_12.setText(_translate("MainWindow", "A", None))
        self.label_11.setText(_translate("MainWindow", "x0", None))
        self.fitted_w.setText(_translate("MainWindow", "FWHM", None))
        self.label_14.setText(_translate("MainWindow", "mu", None))
        self.ruby_lambda0_btn.setText(_translate("MainWindow", "694.24", None))
        self.label_20.setText(_translate("MainWindow", "<html><head/><body><p><font face=\"Symbol\"><font size=\"+1\">l</font></font><sub>0</sub> (nm)</p></body></html>", None))
        self.label_10.setText(_translate("MainWindow", "BG", None))
        self.fitted_xc.setText(_translate("MainWindow", "x0", None))
        self.fitted_A.setText(_translate("MainWindow", "A", None))
        self.fitted_mu.setText(_translate("MainWindow", "mu", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "Ruby Cr:Al2O3", None))
        self.Samarium_non_hydro_btn.setText(_translate("MainWindow", "Non-hydrostatic (Jing 2013)", None))
        self.label_22.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">Fitted results (Samarium peak)</span></p></body></html>", None))
        self.sum_fitted_y0.setText(_translate("MainWindow", "BG", None))
        self.label_27.setText(_translate("MainWindow", "A", None))
        self.sum_fitted_xc.setText(_translate("MainWindow", "x0", None))
        self.sum_fitted_A.setText(_translate("MainWindow", "A", None))
        self.sum_fitted_mu.setText(_translate("MainWindow", "mu", None))
        self.label_29.setText(_translate("MainWindow", "FWHM", None))
        self.label_25.setText(_translate("MainWindow", "x0", None))
        self.label_31.setText(_translate("MainWindow", "mu", None))
        self.sum_fitted_w.setText(_translate("MainWindow", "FWHM", None))
        self.label_23.setText(_translate("MainWindow", "BG", None))
        self.label_33.setText(_translate("MainWindow", "<html><head/><body><p><font face=\"Symbol\"><font size=\"+1\">l</font></font><sub>0</sub> (nm)</p></body></html>", None))
        self.Samarium_lambda0_btn.setText(_translate("MainWindow", "685.51", None))
        self.Samarium_hydro_btn.setText(_translate("MainWindow", "Hydrostatic (Rashchenko 2015)", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Samarium Sr:SrB4O7", None))
        self.pressure_txt.setText(_translate("MainWindow", "<p><span style=\" color:#ff0000;\">P =</span></p>", None))
        self.monitor_pressure_btn.setText(_translate("MainWindow", "Start pressure monitoring", None))
        self.export_pressure_btn.setText(_translate("MainWindow", "Export pressure profile", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionRefresh.setText(_translate("MainWindow", "Refresh", None))
        self.actionRefresh.setToolTip(_translate("MainWindow", "Reload Spectrometer hardware", None))
        self.actionRecord.setText(_translate("MainWindow", "Record", None))
        self.actionRecord.setToolTip(_translate("MainWindow", "Record spectrum", None))
        self.actionDark.setText(_translate("MainWindow", "Dark", None))
        self.actionDark.setToolTip(_translate("MainWindow", "Dark signal subtraction", None))
        self.actionZoom.setText(_translate("MainWindow", "Zoom", None))
        self.actionZoom.setToolTip(_translate("MainWindow", "Zoom", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionSave.setToolTip(_translate("MainWindow", "Save current spectrum to file", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionAbout.setToolTip(_translate("MainWindow", "About this program", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

